
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  messages:
    basename: classpath:/i18n/messages
  thymeleaf:
    mode: XHTML

security:
  basic:
    enabled: false
