spring:
  datasource:

    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/resources?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Bucharest&createDatabaseIfNotExist=true
    username: root
    password: mysql8

    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 4000
        userServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics:
    generate-ddl: true


server:
  port: 8080